name: stock-rater

on:
  schedule:
    - cron: '0 21 * * 1-5'   # Weekdays at 21:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure output dir
        run: mkdir -p output

      - name: Run screener
        run: |
          python app/main.py --tickers-file config/tickers.txt --days 450 --output output/results.csv

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/results.csv
          git commit -m "Update results [skip ci]" || echo "Nothing to commit"
          git push || echo "Push skipped (no token / fork)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: output/results.csv
